# Generated by Django 4.2.1 on 2023-05-18 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arts',
            fields=[
                ('id_art', models.IntegerField(max_length=300, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=300, verbose_name='nombre de arts')),
                ('email', models.CharField(max_length=300, unique=True, verbose_name='email de arts')),
                ('tel', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Datos_Empleados',
            fields=[
                ('dni', models.IntegerField(max_length=300, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=300, verbose_name='nombre del empleado')),
                ('apellido', models.CharField(max_length=300, verbose_name='apellido del empleado')),
                ('d_calle', models.CharField(max_length=300, verbose_name='calle donde vive el empleado')),
                ('d_numero', models.IntegerField()),
                ('depa_provic', models.CharField(max_length=300, verbose_name='depa_provic del empleado')),
                ('email_per', models.CharField(max_length=300, unique=True, verbose_name='email personal del empleado')),
                ('email_wk', models.CharField(max_length=300, unique=True, verbose_name='email de trabajo del empleado')),
                ('tel_per', models.IntegerField()),
                ('tel_wk', models.IntegerField()),
                ('categoria', models.CharField(max_length=300, verbose_name='categoria del empleado')),
                ('fecha_ing', models.DateField()),
                ('fecha_na', models.DateField(verbose_name='fecha de nacimiento')),
                ('pais', models.CharField(max_length=300, verbose_name='pais del empleado')),
                ('provincia', models.CharField(max_length=300, verbose_name='provincia del empleado')),
                ('cuidad', models.CharField(max_length=300, verbose_name='ciudad del empleado')),
                ('código_postal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Datos_Empresas',
            fields=[
                ('cuil', models.IntegerField(max_length=300, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=300, verbose_name='nombre de la empresa')),
                ('d_calle', models.CharField(max_length=300, verbose_name='calle de la empresa')),
                ('d_numero', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id_emp', models.IntegerField(max_length=300, primary_key=True, serialize=False)),
                ('cuil', models.IntegerField()),
                ('dni_emp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='databaseManager.datos_empleados')),
                ('id_art_art', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='databaseManager.arts')),
            ],
        ),
        migrations.CreateModel(
            name='Geo_Empresas',
            fields=[
                ('cp', models.IntegerField(max_length=300, primary_key=True, serialize=False)),
                ('provincia', models.CharField(max_length=300, verbose_name='provincia de la empresa')),
                ('cuidad', models.CharField(max_length=300, verbose_name='ciudad de la empresa')),
                ('pais', models.CharField(max_length=300, verbose_name='pais de la empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Ingresos',
            fields=[
                ('id_ingreso', models.IntegerField(max_length=300, primary_key=True, serialize=False)),
                ('id_ing', models.DateField(verbose_name='id_ing')),
                ('ingresoAnual', models.IntegerField()),
                ('diaDePago', models.DateField(verbose_name='dia de pago')),
                ('diaFinDePago', models.DateField(verbose_name='dia de fin de pago')),
                ('periodoDePago', models.CharField(max_length=300, verbose_name='periodo de ingresos')),
            ],
        ),
        migrations.CreateModel(
            name='Obrassociales',
            fields=[
                ('id_os', models.IntegerField(max_length=300, primary_key=True, serialize=False)),
                ('tel', models.IntegerField()),
                ('email', models.CharField(max_length=300, unique=True, verbose_name='email de la obrasocial')),
                ('nombre', models.CharField(max_length=300, verbose_name='nombre de la obrasocial')),
            ],
        ),
        migrations.CreateModel(
            name='RecibosH',
            fields=[
                ('id_deduc', models.IntegerField(max_length=300, primary_key=True, serialize=False)),
                ('montoB', models.DecimalField(decimal_places=2, max_digits=8)),
                ('periodo', models.DateField(verbose_name='periodo')),
                ('antiguedad', models.IntegerField()),
                ('descrip', models.CharField(max_length=300, verbose_name='descripción de reciboh')),
                ('asisypun', models.IntegerField()),
                ('numero', models.IntegerField()),
                ('f_pago', models.DateField(verbose_name='fecha del pago')),
                ('id_ing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='databaseManager.empleados')),
            ],
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id_servicios', models.IntegerField(max_length=300, primary_key=True, serialize=False)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('nombre', models.CharField(max_length=300, verbose_name='nombre del servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Supervisas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_emp_sa', models.ManyToManyField(blank=True, related_name='id_emp_sa', to='databaseManager.empleados')),
                ('id_emp_so', models.ManyToManyField(blank=True, related_name='id_emp_so', to='databaseManager.empleados')),
            ],
        ),
        migrations.CreateModel(
            name='Reclamos',
            fields=[
                ('id_recla', models.IntegerField(max_length=300, primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=300, verbose_name='estado de reclamo')),
                ('descrip', models.CharField(max_length=300, verbose_name='descripción de reclamo')),
                ('fecha', models.DateField(verbose_name='fecha')),
                ('tipo', models.CharField(max_length=300, verbose_name='tip de reclamo')),
                ('id_emp_emp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='databaseManager.empleados')),
                ('id_rec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='databaseManager.recibosh')),
            ],
        ),
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('id_per', models.IntegerField(max_length=300, primary_key=True, serialize=False)),
                ('per_bool', models.IntegerField()),
                ('id_ser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='databaseManager.servicios')),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('user', models.CharField(max_length=300, primary_key=True, serialize=False, verbose_name='ingresa usuario')),
                ('psw', models.CharField(max_length=300, unique=True, verbose_name='contraseña usuario')),
                ('last_log', models.DateField(verbose_name='últimamente ingresado')),
                ('id_emp_emp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='databaseManager.empleados')),
            ],
        ),
        migrations.CreateModel(
            name='Extras',
            fields=[
                ('tipo', models.CharField(max_length=300, primary_key=True, serialize=False, verbose_name='tipo de extra')),
                ('cantidad_emp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='databaseManager.empleados')),
                ('id_rec', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='databaseManager.recibosh')),
            ],
        ),
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id_impre', models.IntegerField(max_length=300, primary_key=True, serialize=False)),
                ('cuil_datos_empre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='databaseManager.datos_empresas')),
                ('id_serv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='databaseManager.servicios')),
            ],
        ),
        migrations.AddField(
            model_name='empleados',
            name='id_empre_empre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='databaseManager.empresas'),
        ),
        migrations.AddField(
            model_name='empleados',
            name='id_os_os',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='databaseManager.obrassociales'),
        ),
        migrations.CreateModel(
            name='Deducciones',
            fields=[
                ('cod_deduc', models.IntegerField(max_length=300, primary_key=True, serialize=False)),
                ('monto_deduc', models.IntegerField()),
                ('causa_deduc', models.CharField(max_length=300, verbose_name='causa de deducción')),
                ('id_deduc_deduc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='databaseManager.recibosh')),
            ],
        ),
        migrations.AddField(
            model_name='datos_empresas',
            name='cp_geo_empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='databaseManager.geo_empresas'),
        ),
        migrations.CreateModel(
            name='ContrataOs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_empre_empre', models.ManyToManyField(blank=True, to='databaseManager.empresas')),
                ('id_os_os', models.ManyToManyField(blank=True, to='databaseManager.obrassociales')),
            ],
        ),
        migrations.CreateModel(
            name='ContrataAs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_art_art', models.ManyToManyField(blank=True, to='databaseManager.arts')),
                ('id_empre_empre', models.ManyToManyField(blank=True, to='databaseManager.empresas')),
            ],
        ),
    ]
