# Generated by Django 4.2.1 on 2023-05-18 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arts',
            name='id_art',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='datos_empleados',
            name='dni',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='datos_empresas',
            name='cuil',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='deducciones',
            name='cod_deduc',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='id_impre',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='geo_empresas',
            name='cp',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ingresos',
            name='id_ingreso',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='obrassociales',
            name='id_os',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='permisos',
            name='id_per',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='recibosh',
            name='id_deduc',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reclamos',
            name='id_recla',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='id_servicios',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
