# Generated by Django 4.2.1 on 2023-06-06 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaServicios',
            fields=[
                ('id_categoria', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=200, verbose_name='nombre de la categoria')),
            ],
        ),
    ]
