# Generated by Django 4.2.1 on 2023-05-18 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseManager', '0002_alter_arts_id_art_alter_datos_empleados_dni_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='id_emp',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
