# Generated by Django 4.2.1 on 2023-06-06 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('databaseManager', '0002_categoriaservicios'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicioskillcode',
            name='categoria',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='categoria', to='databaseManager.categoriaservicios'),
            preserve_default=False,
        ),
    ]
