# Generated by Django 4.2.1 on 2023-06-06 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('databaseManager', '0003_servicioskillcode_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='art',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databaseManager.art'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='obra_social',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to='databaseManager.obrasocial'),
        ),
    ]
