# Generated by Django 4.2.1 on 2023-06-19 03:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('databaseManager', '0004_alter_empleado_art_alter_empleado_obra_social'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='cantidad',
            new_name='Cvv',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='Empresa',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='medioDePago',
        ),
        migrations.AddField(
            model_name='pedido',
            name='CustomUser',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='nombre_tarjeta',
            field=models.CharField(default=0, max_length=200, verbose_name='nombre de tarjeta de crédito'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='numero_tarjeta',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='vencimiento',
            field=models.DateField(default=0, verbose_name='fecha de vencimiento de tarjeta'),
            preserve_default=False,
        ),
    ]
