# Generated by Django 4.2.1 on 2023-05-18 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseManager', '0004_alter_arts_email_alter_datos_empleados_email_per_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arts',
            name='email',
            field=models.CharField(max_length=200, verbose_name='email de arts'),
        ),
        migrations.AlterField(
            model_name='arts',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='nombre de arts'),
        ),
        migrations.AlterField(
            model_name='datos_empleados',
            name='apellido',
            field=models.CharField(max_length=200, verbose_name='apellido del empleado'),
        ),
        migrations.AlterField(
            model_name='datos_empleados',
            name='categoria',
            field=models.CharField(max_length=200, verbose_name='categoria del empleado'),
        ),
        migrations.AlterField(
            model_name='datos_empleados',
            name='cuidad',
            field=models.CharField(max_length=200, verbose_name='ciudad del empleado'),
        ),
        migrations.AlterField(
            model_name='datos_empleados',
            name='d_calle',
            field=models.CharField(max_length=200, verbose_name='calle donde vive el empleado'),
        ),
        migrations.AlterField(
            model_name='datos_empleados',
            name='depa_provic',
            field=models.CharField(max_length=200, verbose_name='depa_provic del empleado'),
        ),
        migrations.AlterField(
            model_name='datos_empleados',
            name='email_per',
            field=models.CharField(max_length=200, verbose_name='email personal del empleado'),
        ),
        migrations.AlterField(
            model_name='datos_empleados',
            name='email_wk',
            field=models.CharField(max_length=200, verbose_name='email de trabajo del empleado'),
        ),
        migrations.AlterField(
            model_name='datos_empleados',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='nombre del empleado'),
        ),
        migrations.AlterField(
            model_name='datos_empleados',
            name='provincia',
            field=models.CharField(max_length=200, verbose_name='provincia del empleado'),
        ),
        migrations.AlterField(
            model_name='datos_empresas',
            name='d_calle',
            field=models.CharField(max_length=200, verbose_name='calle de la empresa'),
        ),
        migrations.AlterField(
            model_name='datos_empresas',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='nombre de la empresa'),
        ),
        migrations.AlterField(
            model_name='deducciones',
            name='causa_deduc',
            field=models.CharField(max_length=200, verbose_name='causa de deducción'),
        ),
        migrations.AlterField(
            model_name='extras',
            name='tipo',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='tipo de extra'),
        ),
        migrations.AlterField(
            model_name='geo_empresas',
            name='cuidad',
            field=models.CharField(max_length=200, verbose_name='ciudad de la empresa'),
        ),
        migrations.AlterField(
            model_name='geo_empresas',
            name='pais',
            field=models.CharField(max_length=200, verbose_name='pais de la empresa'),
        ),
        migrations.AlterField(
            model_name='geo_empresas',
            name='provincia',
            field=models.CharField(max_length=200, verbose_name='provincia de la empresa'),
        ),
        migrations.AlterField(
            model_name='ingresos',
            name='periodoDePago',
            field=models.CharField(max_length=200, verbose_name='periodo de ingresos'),
        ),
        migrations.AlterField(
            model_name='login',
            name='psw',
            field=models.CharField(max_length=200, verbose_name='contraseña usuario'),
        ),
        migrations.AlterField(
            model_name='login',
            name='user',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='ingresa usuario'),
        ),
        migrations.AlterField(
            model_name='obrassociales',
            name='email',
            field=models.CharField(max_length=200, verbose_name='email de la obrasocial'),
        ),
        migrations.AlterField(
            model_name='obrassociales',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='nombre de la obrasocial'),
        ),
        migrations.AlterField(
            model_name='recibosh',
            name='descrip',
            field=models.CharField(max_length=200, verbose_name='descripción de reciboh'),
        ),
        migrations.AlterField(
            model_name='reclamos',
            name='descrip',
            field=models.CharField(max_length=200, verbose_name='descripción de reclamo'),
        ),
        migrations.AlterField(
            model_name='reclamos',
            name='estado',
            field=models.CharField(max_length=200, verbose_name='estado de reclamo'),
        ),
        migrations.AlterField(
            model_name='reclamos',
            name='tipo',
            field=models.CharField(max_length=200, verbose_name='tip de reclamo'),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='nombre del servicio'),
        ),
    ]
