# Generated by Django 4.2.1 on 2023-06-20 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databaseManager', '0005_customuser_confirm_password'),
        ('databaseManager', '0005_rename_cantidad_pedido_cvv_remove_pedido_empresa_and_more'),
    ]

    operations = [
    ]
