# Generated by Django 5.0.6 on 2024-05-17 00:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseManager', '0005_customuser_confirm_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='idPedido',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
