# Generated by Django 4.2.1 on 2023-05-20 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('databaseManager', '0005_alter_arts_email_alter_arts_nombre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiciosKillCode',
            fields=[
                ('idServicio', models.IntegerField(primary_key=True, serialize=False)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('detalle', models.CharField(max_length=200, verbose_name='detalle de servicio de kill code')),
                ('nombreServicio', models.CharField(max_length=200, verbose_name='nombre de servicio de kill code')),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('idPedido', models.IntegerField(primary_key=True, serialize=False)),
                ('valorTotal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('detalle', models.CharField(max_length=200, verbose_name='detalle de pedidos')),
                ('cantidad', models.IntegerField()),
                ('medioDePedido', models.CharField(max_length=200, verbose_name='medio de pago para pedidos')),
                ('fechaHora', models.DateTimeField()),
                ('idEmpresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='databaseManager.empresas')),
                ('idServicio_killCode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='databaseManager.servicioskillcode')),
            ],
        ),
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('idFactura', models.IntegerField(primary_key=True, serialize=False)),
                ('valorFactura', models.DecimalField(decimal_places=2, max_digits=8)),
                ('detalleFactura', models.CharField(max_length=200, verbose_name='detalle de la factura')),
                ('cuitKillCode', models.IntegerField()),
                ('tipoFactura', models.CharField(max_length=200, verbose_name='tipo de factura')),
                ('IVA', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fechaHora', models.DateTimeField()),
                ('idPedido_ped', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='databaseManager.pedidos')),
            ],
        ),
    ]
