# Generated by Django 4.2.1 on 2023-05-24 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databaseManager', '0006_servicioskillcode_pedidos_facturas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrataos',
            name='id_empre_empre',
        ),
        migrations.RemoveField(
            model_name='contrataos',
            name='id_os_os',
        ),
        migrations.RemoveField(
            model_name='login',
            name='id_emp_emp',
        ),
        migrations.RemoveField(
            model_name='permisos',
            name='id_ser',
        ),
        migrations.RemoveField(
            model_name='supervisas',
            name='id_emp_sa',
        ),
        migrations.RemoveField(
            model_name='supervisas',
            name='id_emp_so',
        ),
        migrations.DeleteModel(
            name='ContrataAs',
        ),
        migrations.DeleteModel(
            name='ContrataOs',
        ),
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.DeleteModel(
            name='Permisos',
        ),
        migrations.DeleteModel(
            name='Supervisas',
        ),
    ]
