# Generated by Django 5.0.6 on 2024-05-17 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseManager', '0006_remove_pedido_empresa_remove_pedido_cantidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='Empresa',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='medioDePago',
        ),
        migrations.AddField(
            model_name='pedido',
            name='CustomUser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='Cvv',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='nombre_tarjeta',
            field=models.CharField(default=1, max_length=200, verbose_name='nombre de tarjeta de crédito'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='numero_tarjeta',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='vencimiento',
            field=models.DateField(default=1, verbose_name='fecha de vencimiento de tarjeta'),
            preserve_default=False,
        ),
    ]
