# Generated by Django 4.2.1 on 2023-05-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseManager', '0007_remove_contrataos_id_empre_empre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datos_empleados',
            old_name='d_calle',
            new_name='calle',
        ),
        migrations.RenameField(
            model_name='datos_empleados',
            old_name='código_postal',
            new_name='casa_piso_numero',
        ),
        migrations.RenameField(
            model_name='datos_empleados',
            old_name='email_per',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='datos_empleados',
            old_name='fecha_ing',
            new_name='fecha_ingreso',
        ),
        migrations.RenameField(
            model_name='datos_empleados',
            old_name='fecha_na',
            new_name='fecha_nacimiento',
        ),
        migrations.RenameField(
            model_name='datos_empleados',
            old_name='dni',
            new_name='legajo',
        ),
        migrations.RenameField(
            model_name='datos_empleados',
            old_name='d_numero',
            new_name='telefono',
        ),
        migrations.RemoveField(
            model_name='datos_empleados',
            name='depa_provic',
        ),
        migrations.RemoveField(
            model_name='datos_empleados',
            name='email_wk',
        ),
        migrations.RemoveField(
            model_name='datos_empleados',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='datos_empleados',
            name='tel_per',
        ),
        migrations.RemoveField(
            model_name='datos_empleados',
            name='tel_wk',
        ),
        migrations.AddField(
            model_name='datos_empleados',
            name='cargo',
            field=models.CharField(default=0, max_length=200, verbose_name='cargo del empleado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datos_empleados',
            name='documento',
            field=models.IntegerField(default=0, verbose_name='numero de documento'),
            preserve_default=False,
        ),
    ]
