# Generated by Django 4.2.1 on 2023-05-24 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('databaseManager', '0008_rename_d_calle_datos_empleados_calle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresas',
            name='cuil_datos_empre',
        ),
        migrations.RemoveField(
            model_name='empresas',
            name='id_serv',
        ),
        migrations.RenameField(
            model_name='datos_empresas',
            old_name='d_calle',
            new_name='calle',
        ),
        migrations.RenameField(
            model_name='datos_empresas',
            old_name='d_numero',
            new_name='numero',
        ),
        migrations.RemoveField(
            model_name='datos_empresas',
            name='cp_geo_empresa',
        ),
        migrations.RemoveField(
            model_name='extras',
            name='cantidad_emp',
        ),
        migrations.RemoveField(
            model_name='recibosh',
            name='id_ing',
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='idEmpresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='databaseManager.datos_empresas'),
        ),
        migrations.AlterField(
            model_name='reclamos',
            name='id_emp_emp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='databaseManager.datos_empleados'),
        ),
        migrations.DeleteModel(
            name='Empleados',
        ),
        migrations.DeleteModel(
            name='Empresas',
        ),
        migrations.DeleteModel(
            name='Geo_Empresas',
        ),
        migrations.DeleteModel(
            name='Servicios',
        ),
    ]
