# Generated by Django 4.2.1 on 2023-05-24 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databaseManager', '0009_remove_empresas_cuil_datos_empre_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ingresos',
        ),
        migrations.RenameField(
            model_name='facturas',
            old_name='idPedido_ped',
            new_name='Pedido',
        ),
        migrations.RenameField(
            model_name='pedidos',
            old_name='idEmpresa',
            new_name='Empresa',
        ),
        migrations.RenameField(
            model_name='pedidos',
            old_name='idServicio_killCode',
            new_name='Servicio',
        ),
    ]
