# Generated by Django 4.2.1 on 2023-05-24 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databaseManager', '0010_delete_ingresos_rename_idpedido_ped_facturas_pedido_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deducciones',
            old_name='causa_deduc',
            new_name='causa_deduccion',
        ),
        migrations.RenameField(
            model_name='deducciones',
            old_name='cod_deduc',
            new_name='cod_deduccion',
        ),
        migrations.RenameField(
            model_name='deducciones',
            old_name='monto_deduc',
            new_name='monto_deduccion',
        ),
        migrations.RenameField(
            model_name='recibosh',
            old_name='f_pago',
            new_name='fecha_pago',
        ),
        migrations.RenameField(
            model_name='recibosh',
            old_name='id_deduc',
            new_name='id_deduccion',
        ),
        migrations.RenameField(
            model_name='reclamos',
            old_name='descrip',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='reclamos',
            old_name='id_emp_emp',
            new_name='empleado',
        ),
        migrations.RenameField(
            model_name='reclamos',
            old_name='id_rec',
            new_name='recibo',
        ),
        migrations.RemoveField(
            model_name='deducciones',
            name='id_deduc_deduc',
        ),
    ]
