# Generated by Django 4.2.1 on 2023-05-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseManager', '0011_rename_causa_deduc_deducciones_causa_deduccion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arts',
            old_name='tel',
            new_name='telefono',
        ),
        migrations.RenameField(
            model_name='obrassociales',
            old_name='id_os',
            new_name='id_ObraSocial',
        ),
        migrations.RenameField(
            model_name='obrassociales',
            old_name='tel',
            new_name='telefono',
        ),
        migrations.RenameField(
            model_name='recibosh',
            old_name='asisypun',
            new_name='asistencia',
        ),
        migrations.RenameField(
            model_name='recibosh',
            old_name='descrip',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='recibosh',
            old_name='id_deduccion',
            new_name='id_recibo',
        ),
        migrations.RenameField(
            model_name='recibosh',
            old_name='numero',
            new_name='monto',
        ),
        migrations.RenameField(
            model_name='recibosh',
            old_name='montoB',
            new_name='montoBruto',
        ),
        migrations.AddField(
            model_name='recibosh',
            name='montoNeto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
