# Generated by Django 4.2.1 on 2023-05-24 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('databaseManager', '0012_rename_tel_arts_telefono_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arts',
            name='empresa',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='databaseManager.datos_empresas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datos_empresas',
            name='empleado',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='databaseManager.datos_empleados'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='obrassociales',
            name='empleado',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='databaseManager.datos_empleados'),
            preserve_default=False,
        ),
    ]
