# Generated by Django 4.2.1 on 2023-05-24 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databaseManager', '0013_arts_empresa_datos_empresas_empleado_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Deducciones',
        ),
        migrations.DeleteModel(
            name='Extras',
        ),
    ]
