# Generated by Django 4.2.1 on 2023-05-24 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('databaseManager', '0014_delete_deducciones_delete_extras'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deducciones',
            fields=[
                ('cod_deduccion', models.IntegerField(primary_key=True, serialize=False)),
                ('monto_deduccion', models.IntegerField()),
                ('causa_deduccion', models.CharField(max_length=200, verbose_name='causa de deducción')),
            ],
        ),
        migrations.CreateModel(
            name='Extras',
            fields=[
                ('cod_extra', models.IntegerField(primary_key=True, serialize=False)),
                ('causa_extra', models.CharField(max_length=200, verbose_name='tipo de extra')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.AddField(
            model_name='recibosh',
            name='deduccion',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='databaseManager.deducciones'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recibosh',
            name='extra',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='databaseManager.extras'),
            preserve_default=False,
        ),
    ]
