# Generated by Django 4.2.1 on 2023-05-24 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('databaseManager', '0015_deducciones_extras_recibosh_deduccion_recibosh_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturas',
            name='Pedido',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='databaseManager.pedidos'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='Empresa',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='databaseManager.datos_empresas'),
        ),
        migrations.AlterField(
            model_name='reclamos',
            name='empleado',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='databaseManager.datos_empleados'),
        ),
        migrations.AlterField(
            model_name='reclamos',
            name='recibo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='databaseManager.recibosh'),
        ),
    ]
