# Generated by Django 4.2.1 on 2023-05-24 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databaseManager', '0016_alter_facturas_pedido_alter_pedidos_empresa_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Datos_Empleados',
            new_name='Empleado',
        ),
        migrations.RenameModel(
            old_name='Datos_Empresas',
            new_name='Empresa',
        ),
        migrations.RenameModel(
            old_name='Obrassociales',
            new_name='ObraSocial',
        ),
    ]
