# Generated by Django 4.2.1 on 2023-05-24 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databaseManager', '0017_rename_datos_empleados_empleado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extras',
            old_name='monto',
            new_name='monto_extra',
        ),
        migrations.RemoveField(
            model_name='recibosh',
            name='monto',
        ),
    ]
