# Generated by Django 4.2.1 on 2023-05-24 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseManager', '0020_rename_documento_empleado_cuil_empleado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre de quien contacta')),
                ('email', models.EmailField(max_length=254)),
                ('comentario', models.CharField(max_length=500)),
            ],
        ),
    ]
