# Generated by Django 4.2.1 on 2023-05-24 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseManager', '0021_contacto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recibosh',
            old_name='descripcion',
            new_name='concepto',
        ),
        migrations.AddField(
            model_name='recibosh',
            name='cantidad',
            field=models.IntegerField(default=0, verbose_name='cantidad de concepto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recibosh',
            name='remuneracion',
            field=models.IntegerField(default=0, verbose_name='remuneracion del concepto por la cantidad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recibosh',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
