# Generated by Django 4.2.1 on 2023-05-24 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databaseManager', '0022_rename_descripcion_recibosh_concepto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='cuidad',
            new_name='ciudad',
        ),
    ]
