# Generated by Django 4.2.1 on 2023-05-24 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseManager', '0023_rename_cuidad_empleado_ciudad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='telefono',
            field=models.BigIntegerField(),
        ),
    ]
