# Generated by Django 4.2.1 on 2023-05-24 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseManager', '0025_alter_empleado_cuil_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arts',
            name='telefono',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='deducciones',
            name='monto_deduccion',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cuit',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='obrasocial',
            name='telefono',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='recibosh',
            name='asistencia',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='recibosh',
            name='remuneracion',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
