# Generated by Django 4.2.1 on 2023-05-24 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('databaseManager', '0027_alter_empresa_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='databaseManager.empleado'),
        ),
    ]
