# Generated by Django 4.2.1 on 2023-05-24 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('databaseManager', '0028_alter_empresa_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='art_contratada',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='aseguradora', to='databaseManager.arts'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='obrasocial',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='databaseManager.empleado'),
        ),
    ]
