# Generated by Django 4.2.1 on 2023-05-24 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databaseManager', '0029_empresa_art_contratada_alter_obrasocial_empleado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obrasocial',
            name='empleado',
        ),
    ]
