# Generated by Django 4.2.1 on 2023-05-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseManager', '0030_remove_obrasocial_empleado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='art',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='calle',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='casa_piso_numero',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='cuil_empleado',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='email',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='fecha_ingreso',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='obra_social',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='provincia',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='art_contratada',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='provincia',
        ),
        migrations.AlterField(
            model_name='reclamos',
            name='tipo',
            field=models.CharField(max_length=200, verbose_name='tipo de reclamo'),
        ),
    ]
