# Generated by Django 4.2.1 on 2023-05-25 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databaseManager', '0030_remove_obrasocial_empleado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deducciones',
            old_name='monto_deduccion',
            new_name='porcentaje_deduccion',
        ),
    ]
