# Generated by Django 4.2.1 on 2023-05-25 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databaseManager', '0031_rename_monto_deduccion_deducciones_porcentaje_deduccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recibosh',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='recibosh',
            name='remuneracion',
        ),
        migrations.RemoveField(
            model_name='recibosh',
            name='valor_unitario',
        ),
    ]
