# Generated by Django 4.2.1 on 2023-05-25 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseManager', '0032_remove_recibosh_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='cuil_empleado',
            field=models.BigIntegerField(verbose_name='cuil del empleado'),
        ),
    ]
