# Generated by Django 4.2.1 on 2023-05-25 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('databaseManager', '0033_alter_empleado_cuil_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibosh',
            name='extra',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='databaseManager.extras'),
        ),
    ]
