# Generated by Django 4.2.1 on 2023-05-30 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databaseManager', '0031_remove_empleado_art_remove_empleado_calle_and_more'),
        ('databaseManager', '0034_alter_recibosh_extra'),
    ]

    operations = [
    ]
