# Generated by Django 4.2.1 on 2023-05-31 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databaseManager', '0035_merge_20230529_2101'),
    ]

    operations = [
    ]
