# Generated by Django 4.2.1 on 2023-05-26 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('databaseManager', '0035_reclamo_rename_arts_art_rename_deducciones_deduccion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='art',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='empleado',
        ),
        migrations.CreateModel(
            name='EmpleadoPorEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databaseManager.empleado')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databaseManager.empresa')),
            ],
        ),
    ]
