# Generated by Django 4.2.1 on 2023-05-26 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databaseManager', '0036_remove_art_empresa_remove_empresa_empleado_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmpleadoPorEmpresa',
        ),
    ]
