# Generated by Django 4.2.1 on 2023-05-31 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databaseManager', '0036_auto_20230530_2106'),
        ('databaseManager', '0037_delete_empleadoporempresa'),
    ]

    operations = [
    ]
