-- la base de datos que nosotros usaremos!! 

-- MySQL Script generated by MySQL Workbench
-- Wed Apr 26 11:04:05 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`datos_empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`datos_empleado` (
  `dni` INT NOT NULL,
  `nombre` VARCHAR(300) NOT NULL,
  `apellido` VARCHAR(300) NOT NULL,
  `d_calle` VARCHAR(300) NOT NULL,
  `d_numero` INT NOT NULL,
  `depa_provic` VARCHAR(50) NOT NULL,
  `email_per` VARCHAR(300) NOT NULL,
  `email_wk` VARCHAR(300) NOT NULL,
  `tel_per` INT NOT NULL,
  `tel_wk` INT NOT NULL,
  `categoria` VARCHAR(300) NOT NULL,
  `fecha_ing` DATE NOT NULL,
  `fecha_na` DATE NOT NULL,
  `país` VARCHAR(300) NOT NULL,
  `provincia` VARCHAR(300) NOT NULL,
  `cuidad` VARCHAR(300) NOT NULL,
  `código_postal` INT(50) NOT NULL,
  PRIMARY KEY (`dni`),
  UNIQUE INDEX `email_per_UNIQUE` (`email_per` ASC) VISIBLE,
  UNIQUE INDEX `email_wk_UNIQUE` (`email_wk` ASC) VISIBLE,
  UNIQUE INDEX `tel_per_UNIQUE` (`tel_per` ASC) VISIBLE,
  UNIQUE INDEX `tel_wk_UNIQUE` (`tel_wk` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `mydb`.`paquete`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`paquete` (
  `id_paq` INT NOT NULL,
  `precio` DECIMAL NOT NULL,
  `limite` VARCHAR(300) NOT NULL,
  `nombre` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`id_paq`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`geo_empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`geo_empresa` (
  `cp` INT NOT NULL,
  `provincia` VARCHAR(300) NOT NULL,
  `ciudad` VARCHAR(300) NOT NULL,
  `Pais` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`cp`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`datos_empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`datos_empresa` (
  `cuil` INT NOT NULL,
  `cp` INT NOT NULL,
  `nombre` VARCHAR(300) NOT NULL,
  `d_calle` VARCHAR(300) NOT NULL,
  `d_num` INT NOT NULL,
  PRIMARY KEY (`cuil`),
  INDEX `cp_idx` (`cp` ASC) VISIBLE,
  CONSTRAINT `cp`
    FOREIGN KEY (`cp`)
    REFERENCES `mydb`.`geo_empresa` (`cp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`empresa` (
  `id_empre` INT NOT NULL,
  `id_paq` INT NOT NULL,
  `cuil` INT NOT NULL,
  PRIMARY KEY (`id_empre`),
  UNIQUE INDEX `cuil_UNIQUE` (`cuil` ASC) VISIBLE,
  INDEX `id_paq_idx` (`id_paq` ASC) VISIBLE,
  CONSTRAINT `id_paq`
    FOREIGN KEY (`id_paq`)
    REFERENCES `mydb`.`paquete` (`id_paq`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cuil`
    FOREIGN KEY (`cuil`)
    REFERENCES `mydb`.`datos_empresa` (`cuil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`art`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`art` (
  `id_art` INT NOT NULL,
  `nombre` VARCHAR(300) NOT NULL,
  `email` VARCHAR(300) NOT NULL,
  `tel` INT NOT NULL,
  PRIMARY KEY (`id_art`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `tel_UNIQUE` (`tel` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`obrasocial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`obrasocial` (
  `id_os` INT NOT NULL,
  `tel` INT NOT NULL,
  `email` VARCHAR(300) NOT NULL,
  `nombre` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`id_os`),
  UNIQUE INDEX `tel_UNIQUE` (`tel` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`empleado` (
  `id_emp` INT NOT NULL,
  `id_empre` INT NOT NULL,
  `id_os` INT NOT NULL,
  `id_art` INT NOT NULL,
  `dni` INT NOT NULL,
  `cuil` INT NOT NULL,
  PRIMARY KEY (`id_emp`),
  UNIQUE INDEX `dni_UNIQUE` (`dni` ASC) VISIBLE,
  INDEX `id_empre_idx` (`id_empre` ASC) VISIBLE,
  INDEX `id_art_idx` (`id_art` ASC) VISIBLE,
  INDEX `id_os_idx` (`id_os` ASC) VISIBLE,
  UNIQUE INDEX `cuil_UNIQUE` (`cuil` ASC) VISIBLE,
  CONSTRAINT `dni`
    FOREIGN KEY (`dni`)
    REFERENCES `mydb`.`datos_empleado` (`dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_empre`
    FOREIGN KEY (`id_empre`)
    REFERENCES `mydb`.`empresa` (`id_empre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_art`
    FOREIGN KEY (`id_art`)
    REFERENCES `mydb`.`art` (`id_art`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_os`
    FOREIGN KEY (`id_os`)
    REFERENCES `mydb`.`obrasocial` (`id_os`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`login` (
  `user` INT NOT NULL,
  `id_emp` INT NOT NULL,
  `psw` VARCHAR(300) NOT NULL,
  `last_log` DATE NOT NULL,
  PRIMARY KEY (`user`),
  INDEX `id_emp_idx` (`id_emp` ASC) VISIBLE,
  CONSTRAINT `id_emp`
    FOREIGN KEY (`id_emp`)
    REFERENCES `mydb`.`empleado` (`id_emp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`reciboH`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`reciboH` (
  `id_deduc` INT NOT NULL,
  `id_ing` INT NOT NULL,
  `montoB` DECIMAL NOT NULL,
  `periodo` DATE NOT NULL,
  `antiguedad` INT NOT NULL,
  `descrip` VARCHAR(1000) NOT NULL,
  `asisypun` TINYINT NOT NULL,
  `numero` INT NOT NULL,
  `f_pago` DATE NOT NULL,
  PRIMARY KEY (`id_deduc`),
  INDEX `id_emp_idx` (`id_ing` ASC) VISIBLE,
  CONSTRAINT `id_emp`
    FOREIGN KEY (`id_ing`)
    REFERENCES `mydb`.`empleado` (`id_emp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`reclamo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`reclamo` (
  `id_recla` INT NOT NULL,
  `id_rec` INT NOT NULL,
  `id_emp` INT NOT NULL,
  `estado` VARCHAR(300) NOT NULL,
  `descrip` VARCHAR(1000) NOT NULL,
  `fecha` DATE NOT NULL,
  `tipo` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`id_recla`),
  INDEX `id_emp_idx` (`id_emp` ASC) VISIBLE,
  INDEX `id_rec_idx` (`id_rec` ASC) VISIBLE,
  CONSTRAINT `id_emp`
    FOREIGN KEY (`id_emp`)
    REFERENCES `mydb`.`empleado` (`id_emp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_rec`
    FOREIGN KEY (`id_rec`)
    REFERENCES `mydb`.`reciboH` (`id_deduc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`supervisa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`supervisa` (
  `id_emp_sa` INT NOT NULL,
  `id_emp_so` INT NOT NULL,
  PRIMARY KEY (`id_emp_sa`, `id_emp_so`),
  CONSTRAINT `id_emp_sa`
    FOREIGN KEY (`id_emp_sa`)
    REFERENCES `mydb`.`empleado` (`id_emp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_emp_so`
    FOREIGN KEY (`id_emp_sa` , `id_emp_so`)
    REFERENCES `mydb`.`empleado` (`id_emp` , `id_emp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Deduccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Deduccion` (
  `cod_deduc` INT NOT NULL,
  `id_deduc` INT NOT NULL,
  `monto_deduc` INT(1000000) NOT NULL,
  `causa_deduc` VARCHAR(1000) NOT NULL,
  PRIMARY KEY (`cod_deduc`, `id_deduc`),
  INDEX `id_rec_idx` (`id_deduc` ASC) VISIBLE,
  CONSTRAINT `id_rec`
    FOREIGN KEY (`id_deduc`)
    REFERENCES `mydb`.`reciboH` (`id_deduc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`extras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`extras` (
  `tipo` VARCHAR(15) NOT NULL,
  `id_rec` INT NOT NULL,
  `cantidad` INT NOT NULL,
  PRIMARY KEY (`tipo`, `id_rec`),
  INDEX `id_rec_idx` (`id_rec` ASC) VISIBLE,
  CONSTRAINT `id_rec`
    FOREIGN KEY (`id_rec`)
    REFERENCES `mydb`.`reciboH` (`id_deduc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`contrataos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`contrataos` (
  `id_empre` INT NOT NULL,
  `id_os` INT NOT NULL,
  PRIMARY KEY (`id_empre`, `id_os`),
  INDEX `id_os_idx` (`id_os` ASC) VISIBLE,
  CONSTRAINT `id_empre`
    FOREIGN KEY (`id_empre`)
    REFERENCES `mydb`.`empresa` (`id_empre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_os`
    FOREIGN KEY (`id_os`)
    REFERENCES `mydb`.`obrasocial` (`id_os`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`permisos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`permisos` (
  `id_per` INT NOT NULL,
  `id_paq` INT NOT NULL,
  `per_bool` TINYINT NOT NULL,
  PRIMARY KEY (`id_per`, `id_paq`),
  INDEX `id_paq_idx` (`id_paq` ASC) VISIBLE,
  CONSTRAINT `id_paq`
    FOREIGN KEY (`id_paq`)
    REFERENCES `mydb`.`paquete` (`id_paq`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`contrataa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`contrataa` (
  `id_empre` INT NOT NULL,
  `id_art` INT NOT NULL,
  PRIMARY KEY (`id_empre`, `id_art`),
  INDEX `id_art_idx` (`id_art` ASC) VISIBLE,
  CONSTRAINT `id_empre`
    FOREIGN KEY (`id_empre`)
    REFERENCES `mydb`.`empresa` (`id_empre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_art`
    FOREIGN KEY (`id_art`)
    REFERENCES `mydb`.`art` (`id_art`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ingreso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ingreso` (
  `id_ingreso` INT NOT NULL,
  `id_ing` DATE NOT NULL,
  `IngresoAnual` INT(1000000) NOT NULL,
  `díaDePago` DATE NOT NULL,
  `díaFinDePago` DATE NOT NULL,
  `periodoDePago` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`id_ingreso`, `id_ing`),
  INDEX `id_rec_idx` (`id_ing` ASC) VISIBLE,
  CONSTRAINT `id_rec0`
    FOREIGN KEY (`id_ing`)
    REFERENCES `mydb`.`reciboH` (`id_deduc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
